// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1cCPj6teO81nWoE_J5zU65khbx2cm2SI',
    appId: '1:247930628183:web:bee09f08b45f70cdc75b12',
    messagingSenderId: '247930628183',
    projectId: 'trashindo-f408a',
    authDomain: 'trashindo-f408a.firebaseapp.com',
    storageBucket: 'trashindo-f408a.firebasestorage.app',
    measurementId: 'G-DWPMYYHXTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiYHgNQTZCtqIwWDuNlW3_TnBlnhFs6wQ',
    appId: '1:247930628183:android:a03bd5e3224d89a9c75b12',
    messagingSenderId: '247930628183',
    projectId: 'trashindo-f408a',
    storageBucket: 'trashindo-f408a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb0hKqUhQl0pC64RV5tTzQR8mNySZEMLg',
    appId: '1:247930628183:ios:78757fcf51840ccbc75b12',
    messagingSenderId: '247930628183',
    projectId: 'trashindo-f408a',
    storageBucket: 'trashindo-f408a.firebasestorage.app',
    iosBundleId: 'com.example.trashindo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb0hKqUhQl0pC64RV5tTzQR8mNySZEMLg',
    appId: '1:247930628183:ios:78757fcf51840ccbc75b12',
    messagingSenderId: '247930628183',
    projectId: 'trashindo-f408a',
    storageBucket: 'trashindo-f408a.firebasestorage.app',
    iosBundleId: 'com.example.trashindo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1cCPj6teO81nWoE_J5zU65khbx2cm2SI',
    appId: '1:247930628183:web:d8751c544dced7a9c75b12',
    messagingSenderId: '247930628183',
    projectId: 'trashindo-f408a',
    authDomain: 'trashindo-f408a.firebaseapp.com',
    storageBucket: 'trashindo-f408a.firebasestorage.app',
    measurementId: 'G-V1XKG5KTBY',
  );
}
